brand_name: Azzoro Resources PLC
logo: /new_logo.png
logo_dark: /new_logo.png
stock_ticker: AZ9
stock_api_enabled: true
investor_portal_url: https://investors.asianbatterymetals.com
social:
  linkedin: https://www.linkedin.com
default_locale: en