brand_name: Azzuro Resources PLC
logo: /logo-azzuro-dark.png
logo_dark: /logo-azzuro-light.png
stock_ticker: AZ9
stock_api_enabled: true
investor_portal_url: https://investors.asianbatterymetals.com
social:
  linkedin: https://www.linkedin.com
default_locale: en